theme: jekyll-theme-architect

title: Ellsa Fiorenza
author:
  name: Ellsa Fiorenza
  email: ellsafiorenza@berkeley.edu

description: Ellsa Fiorenza's personal portfolio 

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    linkedin: ellsa-fiorenza
